export const SIGNER_KIND = Object.freeze({
  SERVER: "server",
  ROBOT: "robot",
  OPERATOR: "operator",
  ROBOT_OR_OPERATOR: "robot_or_operator",
  SERVER_OR_OPERATOR: "server_or_operator",
  SERVER_OR_ROBOT: "server_or_robot",
  NONE: "none"
});

const ROBOT_SIGNED_TYPES = new Set([
  "TELEMETRY_HEARTBEAT",
  "CHECKPOINT_REACHED",
  "EN_ROUTE",
  "ASSIST_REQUESTED",
  "EXECUTION_STARTED",
  "JOB_EXECUTION_STARTED",
  "JOB_HEARTBEAT",
  "EXECUTION_COMPLETED",
  "JOB_EXECUTION_COMPLETED",
  "EXECUTION_ABORTED",
  "INCIDENT_DETECTED",
  "SKILL_METER_REPORTED",
  "ROBOT_HEARTBEAT"
]);

const OPERATOR_SIGNED_TYPES = new Set([
  "ASSIST_STARTED",
  "ASSIST_ENDED",
  "ASSIST_ACCEPTED",
  "ASSIST_DECLINED",
  "OPERATOR_SHIFT_OPENED",
  "OPERATOR_SHIFT_CLOSED"
]);

const ROBOT_OR_OPERATOR_SIGNED_TYPES = new Set(["ACCESS_GRANTED", "ACCESS_DENIED", "SKILL_USED", "ZONE_COVERAGE_REPORTED"]);

const SERVER_OR_OPERATOR_SIGNED_TYPES = new Set(["INCIDENT_REPORTED", "CLAIM_TRIAGED"]);

const SERVER_OR_ROBOT_SIGNED_TYPES = new Set(["EVIDENCE_CAPTURED", "JOB_EXECUTION_ABORTED", "JOB_EXECUTION_RESUMED", "ROBOT_UNHEALTHY"]);

  const SERVER_SIGNED_TYPES = new Set([
  "JOB_CREATED",
  "QUOTE_PROPOSED",
  "RISK_SCORED",
  "BOOKED",
  "DISPATCH_REQUESTED",
  "DISPATCH_EVALUATED",
  "DISPATCH_CONFIRMED",
  "DISPATCH_FAILED",
  "OPERATOR_COVERAGE_RESERVED",
  "OPERATOR_COVERAGE_RELEASED",
  "ASSIST_QUEUED",
  "ASSIST_ASSIGNED",
  "ASSIST_TIMEOUT",
  "MATCHED",
  "RESERVED",
  "SETTLED",
  "JOB_EXECUTION_STALLED",
  "JOB_RESCHEDULED",
  "JOB_CANCELLED",
  "ACCESS_PLAN_ISSUED",
  "ACCESS_REVOKED",
  "ACCESS_EXPIRED",
  "SKILL_LICENSED",
  "CLAIM_OPENED",
  "CLAIM_APPROVED",
  "CLAIM_DENIED",
  "CLAIM_PAID",
  "JOB_ADJUSTED",
  "ROBOT_REGISTERED",
  "ROBOT_AVAILABILITY_SET",
  "ROBOT_QUARANTINED",
  "ROBOT_QUARANTINE_CLEARED",
  "MAINTENANCE_REQUESTED",
  "MAINTENANCE_COMPLETED",
  "ROBOT_STATUS_CHANGED",
  "OPERATOR_REGISTERED",
  "OPERATOR_COST_RECORDED",
  "SLA_BREACH_DETECTED",
  "SLA_CREDIT_ISSUED",
  "PROOF_EVALUATED",
  "PROOF_OVERRIDDEN",
  "SETTLEMENT_HELD",
  "SETTLEMENT_RELEASED",
  "SETTLEMENT_FORFEITED",
  "DISPUTE_OPENED",
  "DISPUTE_CLOSED",
  "EVIDENCE_VIEWED",
  "EVIDENCE_EXPIRED",
  "CORRELATION_LINKED",
  "CORRELATION_RELINKED",
  "MONTH_CLOSE_REQUESTED",
  "MONTH_CLOSED",
  "MONTH_CLOSE_REOPENED",
  "INSURER_REIMBURSEMENT_RECORDED",
  "DECISION_RECORDED",
  "TENANT_POLICY_UPDATED",
  "SERVER_SIGNER_KEY_REGISTERED",
  "SERVER_SIGNER_KEY_ROTATED",
  "SERVER_SIGNER_KEY_REVOKED"
]);

export function requiredSignerKindForEventType(eventType) {
  if (ROBOT_SIGNED_TYPES.has(eventType)) return SIGNER_KIND.ROBOT;
  if (OPERATOR_SIGNED_TYPES.has(eventType)) return SIGNER_KIND.OPERATOR;
  if (ROBOT_OR_OPERATOR_SIGNED_TYPES.has(eventType)) return SIGNER_KIND.ROBOT_OR_OPERATOR;
  if (SERVER_OR_OPERATOR_SIGNED_TYPES.has(eventType)) return SIGNER_KIND.SERVER_OR_OPERATOR;
  if (SERVER_OR_ROBOT_SIGNED_TYPES.has(eventType)) return SIGNER_KIND.SERVER_OR_ROBOT;
  if (SERVER_SIGNED_TYPES.has(eventType)) return SIGNER_KIND.SERVER;
  return SIGNER_KIND.NONE;
}

export function listKnownEventTypes() {
  const all = new Set();
  for (const s of [ROBOT_SIGNED_TYPES, OPERATOR_SIGNED_TYPES, ROBOT_OR_OPERATOR_SIGNED_TYPES, SERVER_OR_OPERATOR_SIGNED_TYPES, SERVER_OR_ROBOT_SIGNED_TYPES, SERVER_SIGNED_TYPES]) {
    for (const t of s) all.add(t);
  }
  return Array.from(all).sort();
}
