name: settld-verify
description: Verify a Settld bundle directory with stable machine-readable output (VerifyCliOutput.v1).

inputs:
  bundle_path:
    description: Path to a bundle directory (JobProof/MonthProof/FinancePack).
    required: true
  strict:
    description: "Strict verification (true/false)."
    required: false
    default: "true"
  fail_on_warnings:
    description: "Fail the action when warnings are present (true/false)."
    required: false
    default: "false"
  hash_concurrency:
    description: "Hashing concurrency (positive integer)."
    required: false
    default: "8"
  trust_file:
    description: Path to a trust.json file containing governanceRoots and optional timeAuthorities.
    required: false
    default: ""
  output_json_path:
    description: Path to write VerifyCliOutput.v1 JSON.
    required: false
    default: "settld-verify-output.json"

outputs:
  status:
    description: pass or fail
    value: ${{ steps.verify.outputs.status }}
  output_json_path:
    description: Path to the written JSON output.
    value: ${{ steps.verify.outputs.output_json_path }}

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install settld-verify (from action source)
      shell: bash
      run: |
        set -euo pipefail
        OUT="${RUNNER_TEMP}/settld-verify-pack"
        rm -rf "$OUT"
        mkdir -p "$OUT"

        # github.action_path resolves to .../.github/actions/settld-verify
        # We need to reach repo-root /packages/artifact-verify.
        PKG_DIR="${{ github.action_path }}/../../../packages/artifact-verify"
        if [[ ! -f "${PKG_DIR}/package.json" ]]; then
          echo "expected package.json at ${PKG_DIR}/package.json" >&2
          exit 2
        fi

        (cd "$PKG_DIR" && npm pack --silent --pack-destination "$OUT" >/dev/null)
        TARBALL="$(ls -1 "$OUT"/*.tgz | head -n 1)"
        npm install -g "$TARBALL" >/dev/null
        settld-verify --version >/dev/null

    - name: Verify bundle
      id: verify
      shell: bash
      run: |
        set -euo pipefail

        BUNDLE_PATH="${{ inputs.bundle_path }}"
        OUT_JSON="${{ inputs.output_json_path }}"
        STRICT="${{ inputs.strict }}"
        FAIL_ON_WARNINGS="${{ inputs.fail_on_warnings }}"
        HASH_CONCURRENCY="${{ inputs.hash_concurrency }}"
        TRUST_FILE="${{ inputs.trust_file }}"

        if [[ -n "$TRUST_FILE" ]]; then
          if [[ ! -f "$TRUST_FILE" ]]; then
            echo "trust_file not found: $TRUST_FILE" >&2
            exit 2
          fi
          node -e '
            import fs from "node:fs";
            const p = process.env.TRUST_FILE;
            const t = JSON.parse(fs.readFileSync(p, "utf8"));
            const gov = t?.governanceRoots ?? {};
            const time = t?.timeAuthorities ?? {};
            process.stdout.write(`SETTLD_TRUSTED_GOVERNANCE_ROOT_KEYS_JSON=${JSON.stringify(gov)}\n`);
            if (time && Object.keys(time).length) {
              process.stdout.write(`SETTLD_TRUSTED_TIME_AUTHORITY_KEYS_JSON=${JSON.stringify(time)}\n`);
            }
          ' >> "$GITHUB_ENV"
        fi

        KIND_FLAG="$(node -e '
          import fs from "node:fs";
          import path from "node:path";
          const dir = process.env.BUNDLE_PATH;
          if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) {
            console.error(`bundle_path is not a directory: ${dir}`);
            process.exit(2);
          }
          const settldPath = path.join(dir, "settld.json");
          if (fs.existsSync(settldPath)) {
            const header = JSON.parse(fs.readFileSync(settldPath, "utf8"));
            if (header?.type === "FinancePackBundle.v1") {
              process.stdout.write("--finance-pack");
              process.exit(0);
            }
          }
          const manifestPath = path.join(dir, "manifest.json");
          if (!fs.existsSync(manifestPath)) {
            console.error("could not detect bundle kind (missing settld.json and manifest.json)");
            process.exit(2);
          }
          const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
          const kind = String(manifest?.kind ?? "");
          if (kind === "JobProofBundle.v1") process.stdout.write("--job-proof");
          else if (kind === "MonthProofBundle.v1") process.stdout.write("--month-proof");
          else {
            console.error(`unsupported/unknown bundle kind: ${kind || "(missing)"}`);
            process.exit(2);
          }
        ' BUNDLE_PATH="$BUNDLE_PATH")"

        ARGS=(--format json --hash-concurrency "$HASH_CONCURRENCY")
        if [[ "$STRICT" == "true" ]]; then ARGS+=(--strict); fi
        if [[ "$FAIL_ON_WARNINGS" == "true" ]]; then ARGS+=(--fail-on-warnings); fi
        ARGS+=("$KIND_FLAG" "$BUNDLE_PATH")

        mkdir -p "$(dirname "$OUT_JSON")" 2>/dev/null || true

        set +e
        settld-verify "${ARGS[@]}" > "$OUT_JSON"
        CODE=$?
        set -e

        STATUS="pass"
        if [[ "$CODE" != "0" ]]; then STATUS="fail"; fi
        echo "status=$STATUS" >> "$GITHUB_OUTPUT"
        echo "output_json_path=$OUT_JSON" >> "$GITHUB_OUTPUT"

        if [[ "$CODE" != "0" ]]; then
          echo "settld-verify failed (exit $CODE). See $OUT_JSON." >&2
          exit "$CODE"
        fi
