name: Quickstart failure (Docker / Compose)
description: Report a failure when running Nooterra quickstarts (x402 gateway, Docker, Compose, etc.)
title: "[quickstart] <short summary>"
labels: ["type:bug", "stream:devex"]
body:
  - type: markdown
    attributes:
      value: |
        For fastest triage, attach a debug bundle from this repo:

        ```bash
        ./scripts/collect-debug.sh
        ```

        Then drag-and-drop the resulting `nooterra-debug-*.tar.gz` (or `.zip`) into this issue.
        Review/redact secrets before sharing (logs can contain secrets).

  - type: input
    id: os
    attributes:
      label: OS
      description: Include version and CPU architecture.
      placeholder: "e.g. macOS 14.3 (Apple Silicon), Ubuntu 22.04 (x86_64), Windows 11 + WSL2"
    validations:
      required: true

  - type: input
    id: docker
    attributes:
      label: Docker version
      description: Paste the `docker version` output (or include it via the debug bundle).
      placeholder: "e.g. Docker version 26.1.3, build ..."
    validations:
      required: true

  - type: input
    id: compose
    attributes:
      label: Docker Compose version
      description: Paste `docker compose version` or `docker-compose version` (or include it via the debug bundle).
      placeholder: "e.g. Docker Compose version v2.27.0"
    validations:
      required: true

  - type: textarea
    id: command
    attributes:
      label: Command(s) run
      description: Exact commands you ran from the repo root (redact secrets).
      render: bash
      placeholder: |
        # example
        docker compose up --build
    validations:
      required: true

  - type: textarea
    id: output
    attributes:
      label: Error output snippet
      description: Paste the key error lines (first/last ~50 lines is usually enough). If you attached a debug bundle, still paste the top-level error here.
      render: text
    validations:
      required: true

  - type: textarea
    id: bundle
    attributes:
      label: Debug bundle attachment
      description: Attach `nooterra-debug-*.tar.gz` (or `.zip`) generated by `./scripts/collect-debug.sh`. Mention the filename here after uploading.
      render: text
      placeholder: "Attached: nooterra-debug-20260214T123456Z.tar.gz"
    validations:
      required: false
