const FEDERATION_BAD_REQUEST_BASE = Object.freeze([
  "FEDERATION_ENVELOPE_INVALID",
  "FEDERATION_ENVELOPE_INVALID_JSON",
  "FEDERATION_PROTOCOL_VERSION_MISMATCH",
  "FEDERATION_ENVELOPE_TYPE_MISMATCH",
  "FEDERATION_INVOCATION_ID_REQUIRED",
  "FEDERATION_ORIGIN_DID_INVALID",
  "FEDERATION_TARGET_DID_INVALID"
]);

const FEDERATION_FORBIDDEN = Object.freeze(["FEDERATION_IDENTITY_MISMATCH", "FEDERATION_UNTRUSTED_COORDINATOR"]);
const FEDERATION_CONFLICT = Object.freeze(["FEDERATION_ENVELOPE_CONFLICT", "FEDERATION_ENVELOPE_IN_FLIGHT"]);
const FEDERATION_SERVICE_UNAVAILABLE = Object.freeze([
  "FEDERATION_NOT_CONFIGURED",
  "FEDERATION_IDENTITY_NOT_CONFIGURED",
  "FEDERATION_TRUST_NOT_CONFIGURED",
  "FEDERATION_NAMESPACE_ROUTE_MISSING"
]);
const FEDERATION_INTERNAL_SERVER_ERROR = Object.freeze(["FEDERATION_FETCH_UNAVAILABLE"]);
const FEDERATION_BAD_GATEWAY = Object.freeze(["FEDERATION_UPSTREAM_UNREACHABLE"]);

export const FEDERATION_ERROR_CODE = Object.freeze({
  ENVELOPE_INVALID: "FEDERATION_ENVELOPE_INVALID",
  ENVELOPE_INVALID_JSON: "FEDERATION_ENVELOPE_INVALID_JSON",
  PROTOCOL_VERSION_MISMATCH: "FEDERATION_PROTOCOL_VERSION_MISMATCH",
  ENVELOPE_TYPE_MISMATCH: "FEDERATION_ENVELOPE_TYPE_MISMATCH",
  INVOCATION_ID_REQUIRED: "FEDERATION_INVOCATION_ID_REQUIRED",
  ORIGIN_DID_INVALID: "FEDERATION_ORIGIN_DID_INVALID",
  TARGET_DID_INVALID: "FEDERATION_TARGET_DID_INVALID",
  CAPABILITY_ID_REQUIRED: "FEDERATION_CAPABILITY_ID_REQUIRED",
  RESULT_STATUS_INVALID: "FEDERATION_RESULT_STATUS_INVALID",
  IDENTITY_MISMATCH: "FEDERATION_IDENTITY_MISMATCH",
  UNTRUSTED_COORDINATOR: "FEDERATION_UNTRUSTED_COORDINATOR",
  ENVELOPE_CONFLICT: "FEDERATION_ENVELOPE_CONFLICT",
  ENVELOPE_IN_FLIGHT: "FEDERATION_ENVELOPE_IN_FLIGHT",
  NOT_CONFIGURED: "FEDERATION_NOT_CONFIGURED",
  IDENTITY_NOT_CONFIGURED: "FEDERATION_IDENTITY_NOT_CONFIGURED",
  TRUST_NOT_CONFIGURED: "FEDERATION_TRUST_NOT_CONFIGURED",
  NAMESPACE_ROUTE_MISSING: "FEDERATION_NAMESPACE_ROUTE_MISSING",
  FETCH_UNAVAILABLE: "FEDERATION_FETCH_UNAVAILABLE",
  UPSTREAM_UNREACHABLE: "FEDERATION_UPSTREAM_UNREACHABLE"
});

export const FEDERATION_OPENAPI_ERROR_CODES = Object.freeze({
  invoke: Object.freeze({
    400: Object.freeze([...FEDERATION_BAD_REQUEST_BASE, FEDERATION_ERROR_CODE.CAPABILITY_ID_REQUIRED]),
    403: FEDERATION_FORBIDDEN,
    409: FEDERATION_CONFLICT,
    500: FEDERATION_INTERNAL_SERVER_ERROR,
    502: FEDERATION_BAD_GATEWAY,
    503: FEDERATION_SERVICE_UNAVAILABLE
  }),
  result: Object.freeze({
    400: Object.freeze([...FEDERATION_BAD_REQUEST_BASE, FEDERATION_ERROR_CODE.RESULT_STATUS_INVALID]),
    403: FEDERATION_FORBIDDEN,
    409: FEDERATION_CONFLICT,
    500: FEDERATION_INTERNAL_SERVER_ERROR,
    502: FEDERATION_BAD_GATEWAY,
    503: FEDERATION_SERVICE_UNAVAILABLE
  })
});
