/**
 * Event type taxonomy — 50+ event types organized by domain.
 * Every observation and action in the system is typed.
 */

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Event domains
// ---------------------------------------------------------------------------

export const EVENT_DOMAINS = [
  'communication',
  'financial',
  'commercial',
  'operational',
  'relationship',
  'agent',
  'system',
] as const;

export type EventDomain = (typeof EVENT_DOMAINS)[number];

// ---------------------------------------------------------------------------
// Event type taxonomy
// ---------------------------------------------------------------------------

export const EVENT_TYPES = {
  // Communication
  'communication.email.received': 'An email was received',
  'communication.email.sent': 'An email was sent',
  'communication.call.started': 'A phone call started',
  'communication.call.ended': 'A phone call ended',
  'communication.message.received': 'A chat message was received',
  'communication.message.sent': 'A chat message was sent',
  'communication.meeting.scheduled': 'A meeting was scheduled',
  'communication.meeting.completed': 'A meeting was completed',
  'communication.meeting.cancelled': 'A meeting was cancelled',

  // Financial
  'financial.invoice.created': 'An invoice was created',
  'financial.invoice.sent': 'An invoice was sent to customer',
  'financial.invoice.updated': 'An invoice was updated',
  'financial.invoice.paid': 'An invoice was paid in full',
  'financial.invoice.overdue': 'An invoice became overdue',
  'financial.invoice.voided': 'An invoice was voided',
  'financial.payment.received': 'A payment was received',
  'financial.payment.sent': 'A payment was sent',
  'financial.payment.failed': 'A payment failed',
  'financial.refund.issued': 'A refund was issued',
  'financial.dispute.opened': 'A payment dispute was opened',
  'financial.dispute.resolved': 'A payment dispute was resolved',
  'financial.charge.created': 'A charge was created',
  'financial.charge.refunded': 'A charge was refunded',

  // Commercial
  'commercial.deal.created': 'A deal/opportunity was created',
  'commercial.deal.advanced': 'A deal moved to next stage',
  'commercial.deal.won': 'A deal was won',
  'commercial.deal.lost': 'A deal was lost',
  'commercial.order.placed': 'An order was placed',
  'commercial.order.fulfilled': 'An order was fulfilled',
  'commercial.order.cancelled': 'An order was cancelled',
  'commercial.quote.created': 'A quote was created',
  'commercial.quote.accepted': 'A quote was accepted',

  // Operational
  'operational.task.created': 'A task was created',
  'operational.task.completed': 'A task was completed',
  'operational.task.failed': 'A task failed',
  'operational.appointment.scheduled': 'An appointment was scheduled',
  'operational.appointment.completed': 'An appointment was completed',
  'operational.appointment.cancelled': 'An appointment was cancelled',
  'operational.ticket.created': 'A support ticket was created',
  'operational.ticket.resolved': 'A support ticket was resolved',

  // Relationship
  'relationship.party.created': 'A new party (customer/vendor/etc) was identified',
  'relationship.party.updated': 'A party\'s information was updated',
  'relationship.party.merged': 'Two party records were merged',
  'relationship.established': 'A new relationship was established between parties',
  'relationship.changed': 'A relationship changed (e.g. customer → churned)',

  // Agent
  'agent.action.proposed': 'An agent proposed an action',
  'agent.action.executed': 'An agent action was executed',
  'agent.action.blocked': 'An agent action was blocked by policy',
  'agent.action.escrowed': 'An agent action was held for approval',
  'agent.action.rolled_back': 'An agent action was rolled back',
  'agent.autonomy.promoted': 'An agent was promoted to higher autonomy',
  'agent.autonomy.demoted': 'An agent was demoted to lower autonomy',

  // System
  'system.prediction.created': 'A prediction was generated by the world model',
  'system.conflict.detected': 'A conflict between data sources was detected',
  'system.conflict.resolved': 'A data conflict was resolved',
  'system.policy.changed': 'A policy was created or updated',
  'system.authority.granted': 'Authority was granted to an agent',
  'system.authority.revoked': 'Authority was revoked from an agent',
  'system.connector.synced': 'A connector completed a sync cycle',
  'system.connector.error': 'A connector encountered an error',
} as const;

export type EventType = keyof typeof EVENT_TYPES;

/** Extract the domain from an event type string */
export function eventDomain(eventType: EventType): EventDomain {
  return eventType.split('.')[0] as EventDomain;
}

// ---------------------------------------------------------------------------
// Event schema
// ---------------------------------------------------------------------------

export const ObjectRefSchema = z.object({
  objectId: z.string(),
  objectType: z.string(),
  role: z.string().optional(), // 'sender', 'recipient', 'subject', 'target'
});

export type ObjectRef = z.infer<typeof ObjectRefSchema>;

export const ProvenanceSchema = z.object({
  sourceSystem: z.string(),     // 'stripe', 'gmail', 'quickbooks'
  sourceId: z.string(),          // ID in the source system
  extractionMethod: z.enum(['api', 'llm', 'rule', 'human']),
  extractionConfidence: z.number().min(0).max(1).default(1),
  rawRef: z.string().optional(), // Reference to raw SourceEvent
});

export type Provenance = z.infer<typeof ProvenanceSchema>;

export const WorldEventSchema = z.object({
  id: z.string(),                               // ULID
  tenantId: z.string(),
  type: z.string(),                              // EventType
  timestamp: z.date(),                           // When it happened in the real world
  recordedAt: z.date(),                          // When we recorded it (bi-temporal)
  sourceType: z.enum(['connector', 'agent', 'human', 'system']),
  sourceId: z.string(),
  objectRefs: z.array(ObjectRefSchema),
  payload: z.record(z.unknown()),
  confidence: z.number().min(0).max(1).default(1),
  provenance: ProvenanceSchema,
  causedBy: z.string().optional(),               // ID of event that caused this
  traceId: z.string(),                           // Propagated trace ID
  hash: z.string(),
  previousHash: z.string().optional(),
});

export type WorldEvent = z.infer<typeof WorldEventSchema>;
