/**
 * E2E Test: Basic Workflow Execution
 * 
 * Tests the complete flow from workflow creation to result delivery.
 */

import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest';
import Fastify from 'fastify';
import { randomUUID } from 'crypto';

const API_URL = process.env.E2E_API_URL || 'http://localhost:3002';
const TEST_API_KEY = process.env.E2E_API_KEY || 'test-e2e-key';

// Mock agent server
let mockAgent: ReturnType<typeof Fastify>;
const MOCK_AGENT_PORT = 4001;

describe('Basic Workflow E2E', () => {
    beforeAll(async () => {
        // Start mock agent
        mockAgent = Fastify();

        // Agent JSON-RPC endpoint
        mockAgent.post('/jsonrpc', async (request, reply) => {
            const body = request.body as any;

            if (body.method === 'tasks/execute') {
                // Simulate processing
                await new Promise(resolve => setTimeout(resolve, 100));

                return reply.send({
                    jsonrpc: '2.0',
                    id: body.id,
                    result: {
                        status: 'completed',
                        output: {
                            summary: 'This is a test summary generated by the mock agent.',
                        },
                    },
                });
            }

            return reply.status(400).send({ error: 'Unknown method' });
        });

        // Agent health endpoint
        mockAgent.get('/nooterra/health', async () => ({
            status: 'healthy',
            version: '1.0.0',
            capabilities: ['cap.summarize.v1'],
            queue: { pending: 0, processing: 0, maxConcurrent: 10 },
        }));

        await mockAgent.listen({ port: MOCK_AGENT_PORT });
        console.log(`Mock agent running on port ${MOCK_AGENT_PORT}`);
    });

    afterAll(async () => {
        await mockAgent?.close();
    });

    it('should execute a simple single-node workflow', async () => {
        // Skip if no real coordinator running
        if (!process.env.E2E_API_URL) {
            console.log('Skipping E2E test - no E2E_API_URL set');
            return;
        }

        // 1. Register mock agent
        const registerRes = await fetch(`${API_URL}/v1/agents`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-api-key': TEST_API_KEY,
            },
            body: JSON.stringify({
                name: 'E2E Test Agent',
                endpoint: `http://localhost:${MOCK_AGENT_PORT}`,
                capabilities: ['cap.summarize.v1'],
            }),
        });

        expect(registerRes.status).toBe(200);
        const agent = await registerRes.json();
        console.log('Registered agent:', agent.did);

        // 2. Create workflow
        const workflowId = `e2e-test-${randomUUID()}`;
        const createRes = await fetch(`${API_URL}/v1/workflows`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-api-key': TEST_API_KEY,
            },
            body: JSON.stringify({
                id: workflowId,
                name: 'E2E Test Workflow',
                nodes: [
                    {
                        name: 'summarize',
                        capability: 'cap.summarize.v1',
                        input: { text: 'This is a long document that needs summarizing...' },
                    },
                ],
            }),
        });

        expect(createRes.status).toBe(200);
        const workflow = await createRes.json();
        console.log('Created workflow:', workflow.id);

        // 3. Trigger workflow
        const triggerRes = await fetch(`${API_URL}/v1/workflows/${workflow.id}/trigger`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'x-api-key': TEST_API_KEY,
            },
        });

        expect(triggerRes.status).toBe(200);
        const run = await triggerRes.json();
        console.log('Started run:', run.runId);

        // 4. Poll for completion (max 10s)
        let result;
        for (let i = 0; i < 20; i++) {
            await new Promise(resolve => setTimeout(resolve, 500));

            const statusRes = await fetch(`${API_URL}/v1/workflows/${workflow.id}/runs/${run.runId}`, {
                headers: { 'x-api-key': TEST_API_KEY },
            });

            const status = await statusRes.json();
            if (status.status === 'completed') {
                result = status;
                break;
            }
            if (status.status === 'failed') {
                throw new Error(`Workflow failed: ${status.error}`);
            }
        }

        expect(result).toBeDefined();
        expect(result.status).toBe('completed');
        expect(result.results.summarize.summary).toBeDefined();
        console.log('Workflow completed:', result.results);
    });
});
